squid:
  build: .
#  image: 0dataexpert0/squid:3.5.27-1
  container_name: squid1
  ports:
    - "5128:5128"
  volumes:
    - ./cache/:/var/spool/squid/
    - ./squid.conf:/etc/squid/squid.conf
    - ./squid_passwd:/etc/squid/squid_passwd
  restart: always
